### ISSUE TITLE
ERROR: object 'studies' not found

### ISSUE THREAD

**Issue by mekline** [manybabies/validator#7]
Documenting a workaround I've had to do to get the validator working on my system: 

The 'studies' object doesn't seem to be in scope (?) when I run the server.R app. Copy-pasting lines 7-9 into my console to load that variable and then running again serves as a temporary solution.

(I originally thought this was a problem loading tidyverse, but it wasn't)

**Comment by brandmaier** [comment]
With my latest commit that was merged by Frank, the issue should be resolved and closed.
